export const MEDICATIONS = [
  {
    name: "Ciprofloxacino",
    category: "antibiotic" as const,
    dosage: "500 mg",
    frequency: "Cada 12h",
    mealtimes: ["desayuno", "cena"],
    startDay: 0,
    durationDays: 7,
    mandatory: true,
    instructions: "Tomar con agua. Evitar lacteos 2h antes/despues.",
  },
  {
    name: "Paracetamol",
    category: "painkiller" as const,
    dosage: "1 g",
    frequency: "Cada 8h",
    mealtimes: ["desayuno", "comida", "cena"],
    startDay: 0,
    durationDays: 3,
    mandatory: true,
    instructions: "Primeros 3 dias pautado. Despues a demanda. Max 4g/dia.",
  },
  {
    name: "Prednisona",
    category: "anti_inflammatory" as const,
    dosage: "30 mg",
    frequency: "Cada 24h",
    mealtimes: ["desayuno"],
    startDay: 0,
    durationDays: 5,
    mandatory: true,
    instructions: "Incluido dia de la intervencion. Antiinflamatorio.",
  },
  {
    name: "Omeprazol",
    category: "gastric_protector" as const,
    dosage: "20 mg",
    frequency: "Cada 24h",
    mealtimes: ["desayuno"],
    startDay: 0,
    durationDays: 7,
    mandatory: false,
    instructions: "Protector gastrico recomendado mientras dure la medicacion.",
  },
] as const;
